Namespace Images.BuiltIn

    Public NotInheritable Class Chart
        Inherits ImageMSO

        Private Sub New(value As Integer, name As String)
            MyBase.New(value, name)
        End Sub

        Public Shared ReadOnly Property Chart3DBarChart As Chart = New Chart(1, NameOf(Chart3DBarChart))
        Public Shared ReadOnly Property Chart3DColumnChart As Chart = New Chart(2, NameOf(Chart3DColumnChart))
        Public Shared ReadOnly Property Chart3DConeChart As Chart = New Chart(3, NameOf(Chart3DConeChart))
        Public Shared ReadOnly Property Chart3DPieChart As Chart = New Chart(4, NameOf(Chart3DPieChart))
        Public Shared ReadOnly Property Chart3DView As Chart = New Chart(5, NameOf(Chart3DView))
        Public Shared ReadOnly Property ChartAreaChart As Chart = New Chart(6, NameOf(ChartAreaChart))
        Public Shared ReadOnly Property ChartAxes As Chart = New Chart(7, NameOf(ChartAxes))
        Public Shared ReadOnly Property ChartAxisTitles As Chart = New Chart(8, NameOf(ChartAxisTitles))
        Public Shared ReadOnly Property ChartChangeType As Chart = New Chart(9, NameOf(ChartChangeType))
        Public Shared ReadOnly Property ChartDataLabel As Chart = New Chart(10, NameOf(ChartDataLabel))
        Public Shared ReadOnly Property ChartDataTable As Chart = New Chart(11, NameOf(ChartDataTable))
        Public Shared ReadOnly Property ChartDepthAxis As Chart = New Chart(12, NameOf(ChartDepthAxis))
        Public Shared ReadOnly Property ChartDepthAxisTitle As Chart = New Chart(13, NameOf(ChartDepthAxisTitle))
        Public Shared ReadOnly Property ChartDepthGridlines As Chart = New Chart(14, NameOf(ChartDepthGridlines))
        Public Shared ReadOnly Property ChartEditDataSource As Chart = New Chart(15, NameOf(ChartEditDataSource))
        Public Shared ReadOnly Property ChartElementSelector As Chart = New Chart(16, NameOf(ChartElementSelector))
        Public Shared ReadOnly Property ChartErrorBars As Chart = New Chart(17, NameOf(ChartErrorBars))
        Public Shared ReadOnly Property ChartFloor As Chart = New Chart(18, NameOf(ChartFloor))
        Public Shared ReadOnly Property ChartFormatAxis As Chart = New Chart(19, NameOf(ChartFormatAxis))
        Public Shared ReadOnly Property ChartFormatAxisTitle As Chart = New Chart(20, NameOf(ChartFormatAxisTitle))
        Public Shared ReadOnly Property ChartFormatBackWall As Chart = New Chart(21, NameOf(ChartFormatBackWall))
        Public Shared ReadOnly Property ChartFormatChartArea As Chart = New Chart(22, NameOf(ChartFormatChartArea))
        Public Shared ReadOnly Property ChartFormatChartTitle As Chart = New Chart(23, NameOf(ChartFormatChartTitle))
        Public Shared ReadOnly Property ChartFormatDataLabel As Chart = New Chart(24, NameOf(ChartFormatDataLabel))
        Public Shared ReadOnly Property ChartFormatDataLabels As Chart = New Chart(25, NameOf(ChartFormatDataLabels))
        Public Shared ReadOnly Property ChartFormatDataPoint As Chart = New Chart(26, NameOf(ChartFormatDataPoint))
        Public Shared ReadOnly Property ChartFormatDataSeries As Chart = New Chart(27, NameOf(ChartFormatDataSeries))
        Public Shared ReadOnly Property ChartFormatDataTable As Chart = New Chart(28, NameOf(ChartFormatDataTable))
        Public Shared ReadOnly Property ChartFormatDisplayUnit As Chart = New Chart(29, NameOf(ChartFormatDisplayUnit))
        Public Shared ReadOnly Property ChartFormatDownBars As Chart = New Chart(30, NameOf(ChartFormatDownBars))
        Public Shared ReadOnly Property ChartFormatDropLines As Chart = New Chart(31, NameOf(ChartFormatDropLines))
        Public Shared ReadOnly Property ChartFormatErrorBars As Chart = New Chart(32, NameOf(ChartFormatErrorBars))
        Public Shared ReadOnly Property ChartFormatFloor As Chart = New Chart(33, NameOf(ChartFormatFloor))
        Public Shared ReadOnly Property ChartFormatGridlines As Chart = New Chart(34, NameOf(ChartFormatGridlines))
        Public Shared ReadOnly Property ChartFormatHighLowLine As Chart = New Chart(35, NameOf(ChartFormatHighLowLine))
        Public Shared ReadOnly Property ChartFormatLeaderLines As Chart = New Chart(36, NameOf(ChartFormatLeaderLines))
        Public Shared ReadOnly Property ChartFormatLegend As Chart = New Chart(37, NameOf(ChartFormatLegend))
        Public Shared ReadOnly Property ChartFormatLegendEntry As Chart = New Chart(38, NameOf(ChartFormatLegendEntry))
        Public Shared ReadOnly Property ChartFormatPlotArea As Chart = New Chart(39, NameOf(ChartFormatPlotArea))
        Public Shared ReadOnly Property ChartFormatSelection As Chart = New Chart(40, NameOf(ChartFormatSelection))
        Public Shared ReadOnly Property ChartFormatSeriesLine As Chart = New Chart(41, NameOf(ChartFormatSeriesLine))
        Public Shared ReadOnly Property ChartFormatSideWall As Chart = New Chart(42, NameOf(ChartFormatSideWall))
        Public Shared ReadOnly Property ChartFormatTrendline As Chart = New Chart(43, NameOf(ChartFormatTrendline))
        Public Shared ReadOnly Property ChartFormatTrendlineLabel As Chart = New Chart(44, NameOf(ChartFormatTrendlineLabel))
        Public Shared ReadOnly Property ChartFormatUpBars As Chart = New Chart(45, NameOf(ChartFormatUpBars))
        Public Shared ReadOnly Property ChartFormatWalls As Chart = New Chart(46, NameOf(ChartFormatWalls))
        Public Shared ReadOnly Property ChartGridlines As Chart = New Chart(47, NameOf(ChartGridlines))
        Public Shared ReadOnly Property ChartInsert As Chart = New Chart(48, NameOf(ChartInsert))
        Public Shared ReadOnly Property ChartLayoutGallery As Chart = New Chart(49, NameOf(ChartLayoutGallery))
        Public Shared ReadOnly Property ChartLegend As Chart = New Chart(50, NameOf(ChartLegend))
        Public Shared ReadOnly Property ChartLines As Chart = New Chart(51, NameOf(ChartLines))
        Public Shared ReadOnly Property ChartMoreElement As Chart = New Chart(52, NameOf(ChartMoreElement))
        Public Shared ReadOnly Property ChartPlacement As Chart = New Chart(53, NameOf(ChartPlacement))
        Public Shared ReadOnly Property ChartPlotArea As Chart = New Chart(54, NameOf(ChartPlotArea))
        Public Shared ReadOnly Property ChartPrimaryHorizontalAxis As Chart = New Chart(55, NameOf(ChartPrimaryHorizontalAxis))
        Public Shared ReadOnly Property ChartPrimaryHorizontalAxisTitle As Chart = New Chart(56, NameOf(ChartPrimaryHorizontalAxisTitle))
        Public Shared ReadOnly Property ChartPrimaryHorizontalGridlines As Chart = New Chart(57, NameOf(ChartPrimaryHorizontalGridlines))
        Public Shared ReadOnly Property ChartPrimaryVerticalAxis As Chart = New Chart(58, NameOf(ChartPrimaryVerticalAxis))
        Public Shared ReadOnly Property ChartPrimaryVerticalAxisTitle As Chart = New Chart(59, NameOf(ChartPrimaryVerticalAxisTitle))
        Public Shared ReadOnly Property ChartPrimaryVerticalGridlines As Chart = New Chart(60, NameOf(ChartPrimaryVerticalGridlines))
        Public Shared ReadOnly Property ChartRadarChart As Chart = New Chart(61, NameOf(ChartRadarChart))
        Public Shared ReadOnly Property ChartRefresh As Chart = New Chart(62, NameOf(ChartRefresh))
        Public Shared ReadOnly Property ChartResetToMatchStyle As Chart = New Chart(63, NameOf(ChartResetToMatchStyle))
        Public Shared ReadOnly Property ChartSaveTemplates As Chart = New Chart(64, NameOf(ChartSaveTemplates))
        Public Shared ReadOnly Property ChartSecondaryHorizontalAxis As Chart = New Chart(65, NameOf(ChartSecondaryHorizontalAxis))
        Public Shared ReadOnly Property ChartSecondaryHorizontalAxisTitle As Chart = New Chart(66, NameOf(ChartSecondaryHorizontalAxisTitle))
        Public Shared ReadOnly Property ChartSecondaryHorizontalGridlines As Chart = New Chart(67, NameOf(ChartSecondaryHorizontalGridlines))
        Public Shared ReadOnly Property ChartSecondaryVerticalAxis As Chart = New Chart(68, NameOf(ChartSecondaryVerticalAxis))
        Public Shared ReadOnly Property ChartSecondaryVerticalAxisTitle As Chart = New Chart(69, NameOf(ChartSecondaryVerticalAxisTitle))
        Public Shared ReadOnly Property ChartSecondaryVerticalGridlines As Chart = New Chart(70, NameOf(ChartSecondaryVerticalGridlines))
        Public Shared ReadOnly Property ChartSeriesTypeChange As Chart = New Chart(71, NameOf(ChartSeriesTypeChange))
        Public Shared ReadOnly Property ChartShowData As Chart = New Chart(72, NameOf(ChartShowData))
        Public Shared ReadOnly Property ChartShowDataContextualMenu As Chart = New Chart(73, NameOf(ChartShowDataContextualMenu))
        Public Shared ReadOnly Property ChartSourceDataContextualMenu As Chart = New Chart(74, NameOf(ChartSourceDataContextualMenu))
        Public Shared ReadOnly Property ChartStylesGallery As Chart = New Chart(75, NameOf(ChartStylesGallery))
        Public Shared ReadOnly Property ChartSwitchRowColumn As Chart = New Chart(76, NameOf(ChartSwitchRowColumn))
        Public Shared ReadOnly Property ChartTitle As Chart = New Chart(77, NameOf(ChartTitle))
        Public Shared ReadOnly Property ChartTrendline As Chart = New Chart(78, NameOf(ChartTrendline))
        Public Shared ReadOnly Property ChartTypeAllInsertDialog As Chart = New Chart(79, NameOf(ChartTypeAllInsertDialog))
        Public Shared ReadOnly Property ChartTypeAreaInsertGallery As Chart = New Chart(80, NameOf(ChartTypeAreaInsertGallery))
        Public Shared ReadOnly Property ChartTypeBarInsertGallery As Chart = New Chart(81, NameOf(ChartTypeBarInsertGallery))
        Public Shared ReadOnly Property ChartTypeColumnInsertGallery As Chart = New Chart(82, NameOf(ChartTypeColumnInsertGallery))
        Public Shared ReadOnly Property ChartTypeLineInsertGallery As Chart = New Chart(83, NameOf(ChartTypeLineInsertGallery))
        Public Shared ReadOnly Property ChartTypeOtherInsertGallery As Chart = New Chart(84, NameOf(ChartTypeOtherInsertGallery))
        Public Shared ReadOnly Property ChartTypePieInsertGallery As Chart = New Chart(85, NameOf(ChartTypePieInsertGallery))
        Public Shared ReadOnly Property ChartTypeXYScatterInsertGallery As Chart = New Chart(86, NameOf(ChartTypeXYScatterInsertGallery))
        Public Shared ReadOnly Property ChartUpDownBars As Chart = New Chart(87, NameOf(ChartUpDownBars))
        Public Shared ReadOnly Property ChartWall As Chart = New Chart(88, NameOf(ChartWall))
        Public Shared ReadOnly Property ControlChart As Chart = New Chart(89, NameOf(ControlChart))
        Public Shared ReadOnly Property GroupChartAnalysis As Chart = New Chart(90, NameOf(GroupChartAnalysis))
        Public Shared ReadOnly Property GroupChartAxes As Chart = New Chart(91, NameOf(GroupChartAxes))
        Public Shared ReadOnly Property GroupChartBackground As Chart = New Chart(92, NameOf(GroupChartBackground))
        Public Shared ReadOnly Property GroupChartCurrentSelection As Chart = New Chart(93, NameOf(GroupChartCurrentSelection))
        Public Shared ReadOnly Property GroupChartData As Chart = New Chart(94, NameOf(GroupChartData))
        Public Shared ReadOnly Property GroupChartLabels As Chart = New Chart(95, NameOf(GroupChartLabels))
        Public Shared ReadOnly Property GroupChartLayouts As Chart = New Chart(96, NameOf(GroupChartLayouts))
        Public Shared ReadOnly Property GroupChartLocation As Chart = New Chart(97, NameOf(GroupChartLocation))
        Public Shared ReadOnly Property GroupChartProperties As Chart = New Chart(98, NameOf(GroupChartProperties))
        Public Shared ReadOnly Property GroupChartShapes As Chart = New Chart(99, NameOf(GroupChartShapes))
        Public Shared ReadOnly Property GroupChartStyles As Chart = New Chart(100, NameOf(GroupChartStyles))
        Public Shared ReadOnly Property GroupChartType As Chart = New Chart(101, NameOf(GroupChartType))
        Public Shared ReadOnly Property GroupInsertChartsExcel As Chart = New Chart(102, NameOf(GroupInsertChartsExcel))
        Public Shared ReadOnly Property GroupOrganizationChartLayoutClassic As Chart = New Chart(103, NameOf(GroupOrganizationChartLayoutClassic))
        Public Shared ReadOnly Property GroupOrganizationChartSelect As Chart = New Chart(104, NameOf(GroupOrganizationChartSelect))
        Public Shared ReadOnly Property GroupOrganizationChartShapeInsert As Chart = New Chart(105, NameOf(GroupOrganizationChartShapeInsert))
        Public Shared ReadOnly Property GroupOrganizationChartStyleClassic As Chart = New Chart(106, NameOf(GroupOrganizationChartStyleClassic))
        Public Shared ReadOnly Property OrganizationChartAutoLayout As Chart = New Chart(107, NameOf(OrganizationChartAutoLayout))
        Public Shared ReadOnly Property OrganizationChartInsert As Chart = New Chart(108, NameOf(OrganizationChartInsert))
        Public Shared ReadOnly Property OrganizationChartInsertAssistant As Chart = New Chart(109, NameOf(OrganizationChartInsertAssistant))
        Public Shared ReadOnly Property OrganizationChartInsertCoworker As Chart = New Chart(110, NameOf(OrganizationChartInsertCoworker))
        Public Shared ReadOnly Property OrganizationChartInsertSubordinate As Chart = New Chart(111, NameOf(OrganizationChartInsertSubordinate))
        Public Shared ReadOnly Property OrganizationChartLayoutBothHanging As Chart = New Chart(112, NameOf(OrganizationChartLayoutBothHanging))
        Public Shared ReadOnly Property OrganizationChartLayoutLeftHanging As Chart = New Chart(113, NameOf(OrganizationChartLayoutLeftHanging))
        Public Shared ReadOnly Property OrganizationChartLayoutRightHanging As Chart = New Chart(114, NameOf(OrganizationChartLayoutRightHanging))
        Public Shared ReadOnly Property OrganizationChartLayoutStandard As Chart = New Chart(115, NameOf(OrganizationChartLayoutStandard))
        Public Shared ReadOnly Property OrganizationChartResize As Chart = New Chart(116, NameOf(OrganizationChartResize))
        Public Shared ReadOnly Property OrganizationChartSelectAllAssistants As Chart = New Chart(117, NameOf(OrganizationChartSelectAllAssistants))
        Public Shared ReadOnly Property OrganizationChartSelectAllConnectors As Chart = New Chart(118, NameOf(OrganizationChartSelectAllConnectors))
        Public Shared ReadOnly Property OrganizationChartSelectBranch As Chart = New Chart(119, NameOf(OrganizationChartSelectBranch))
        Public Shared ReadOnly Property OrganizationChartSelectLevel As Chart = New Chart(120, NameOf(OrganizationChartSelectLevel))
        Public Shared ReadOnly Property OrganizationChartStyle As Chart = New Chart(121, NameOf(OrganizationChartStyle))
        Public Shared ReadOnly Property OrgChartScale As Chart = New Chart(122, NameOf(OrgChartScale))
        Public Shared ReadOnly Property SlideMasterChartPlaceholderInsert As Chart = New Chart(123, NameOf(SlideMasterChartPlaceholderInsert))
        Public Shared ReadOnly Property SmartArtOrganizationChartBoth As Chart = New Chart(124, NameOf(SmartArtOrganizationChartBoth))
        Public Shared ReadOnly Property SmartArtOrganizationChartLeftHanging As Chart = New Chart(125, NameOf(SmartArtOrganizationChartLeftHanging))
        Public Shared ReadOnly Property SmartArtOrganizationChartMenu As Chart = New Chart(126, NameOf(SmartArtOrganizationChartMenu))
        Public Shared ReadOnly Property SmartArtOrganizationChartRightHanging As Chart = New Chart(127, NameOf(SmartArtOrganizationChartRightHanging))
        Public Shared ReadOnly Property SmartArtOrganizationChartStandard As Chart = New Chart(128, NameOf(SmartArtOrganizationChartStandard))


        Public Overrides Function Clone() As Object
            Return New Chart(value, name)
        End Function

    End Class

End Namespace